/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://khxovqxuvndczeoa76emylgoma.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zektusuvlbgqrhsvaiwgqetlii",
    "aws_cognito_identity_pool_id": "us-east-1:ac2c7638-ced8-4af5-a273-3cffeb5f608c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_HmCAg9N5j",
    "aws_user_pools_web_client_id": "7vf27gcrc7onblfpig9pac9mj3",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "hrp2b6ffb3229894d9ab85e015e2b161bd00d436-main",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
